version: '3.8'

services:
  rag-api:
    build: .
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - .:/app
      - rag-data:/app/data
      - rag-cache:/app/cache
      - rag-logs:/app/logs
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=sqlite:///./rag_system.db
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  rag-data:
  rag-cache:
  rag-logs:
  redis-data: